import ProjectDescription

let workspace = Workspace(
	name: "GaeManda",
	projects: [
		"Projects/App",
		"Projects/Core",
		"Projects/Data",
		"Projects/DesignKit",
		"Projects/Domain",
		"Projects/GMDClustering",
		"Projects/Presentation/Chatting",
		"Projects/Presentation/GMDMap",
		"Projects/Presentation/SignIn",
		"Projects/Presentation/OnBoarding"
	],
	schemes: [
		Scheme(
			name: "Dev-GaeManda",
			buildAction: .buildAction(targets: [.project(path: "Projects/App", target: "Dev-GaeManda")]),
			runAction: .runAction(configuration: .debug),
			archiveAction: .archiveAction(configuration: .debug),
			profileAction: .profileAction(configuration: .debug),
			analyzeAction: .analyzeAction(configuration: .debug)
		),
		Scheme(
			name: "Prod-GaeManda",
			buildAction: .buildAction(targets: [.project(path: "Projects/App", target: "Prod-GaeManda")]),
			runAction: .runAction(configuration: .release),
			archiveAction: .archiveAction(configuration: .release),
			profileAction: .profileAction(configuration: .release),
			analyzeAction: .analyzeAction(configuration: .release)
		)
	],
	generationOptions: .options(autogeneratedWorkspaceSchemes: .disabled)
)
